name: Daily Build

on:
  schedule:
    # # At 18:50 UTC on everyday (12.20 mid night in Sri Lanka)
    - cron: "50 18 * * *"

  # Enables a button on Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          ref: main

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

# -------------------------------------------------------------------------------------

      - name: "Students API: Generate Student API files"
        run: |
          cd ./python_scripts
          python3 students.py
          cd ../

      - name: "Staff API: Generate Academic Staff API files"
        run: |
          cd ./python_scripts
          python3 staff.py
          cd ../

      - name: "Projects API: Generate Project files"
        run: |
          cd ./python_scripts
          python3 projects.py
          cd ../

      - name: "Projects API: Filter the Projects by Student ENumbers and Tags"
        run: |
          cd ./python_scripts
          python3 projects_filters.py
          cd ../

      - name: "Location API: Update location details from Google Sheet"
        run: |
          cd ./python_scripts
          python3 locations.py
          cd ../

# -------------------------------------------------------------------------------------
 
      - name: Commit and push into the main branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add --all
          git commit -m "Daily build by GitHub Actions" || echo "No changes to commit on People API"
          git push
