name: Publications API

on:
  schedule:
    # # At 18:40 UTC on everyday (12.20 mid night in Sri Lanka)
    - cron: "50 18 * * *"

  # Enables a button on Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          ref: main

      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests


      - name: Send the notifications to Discord
        run: |
          cd ./python_scripts
          python3 publication_notificator.py
          cd ../
