name: Workflow Check

on:
  schedule:
    # # At 20:00 UTC on everyday (1.30 AM in Sri Lanka)
    - cron: "00 20 * * *"

  # Enables a button on Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      webhook_url: ${{ secrets.NOTIFICATION_WEBHOOK_URL }}
    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          ref: main

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pytz
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: "Workflows Status Check and update information"
        run: |
          cd ./python_scripts
          python3 workflows.py
          cd ../

      - name: Commit and push into the main branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add --all
          git commit -m "Daily build by GitHub Actions" || echo "No changes to commit on People API"
          git push
